### ISSUE TITLE
Debugging error

### ISSUE THREAD

**Issue by jalbstmeijer** [static-dev/spike#73] opened 2017-07-06 13:34 UTC
Hi,

Can you please tell me how someone is supposed to debug an error like this; (the id is random)

# spike compile
✗ ERROR
{ [Error] id: '25067473' }

Gr, Justin

**Comment by jescalan** [comment] 2017-07-06 13:36
Hi @jalbstmeijer -- no I can not, it certainly should be more clear than this. Most generated errors come from webpack, which spike is built on top of. Can you show me how to reproduce this error? If so I might be able to help.

**Comment by jalbstmeijer** [comment] 2017-07-06 13:44
info to reproduce:

installed:
nodejs@6.9.5
spike@latest
spike-rooftop@latest
babel-preset-latest@latest
webpack@latest
hard-source-webpack-plugin@latest
spike-html-standards@latest

This was a working app.js, no need to actually have a cms server, as filling in a non existing url gives the same error:
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('babel-preset-env')
const dynamicImport = require('babel-plugin-syntax-dynamic-import')
const pageId = require('spike-page-id')
const Rooftop = require('spike-rooftop')
const locals = {}

module.exports = {
  devtool: 'source-map',
  matchers: {
    html: '*(**/)*.sgr',
    css: '*(**/)*.sss'
  },
  ignore: ['**/layout.sgr', '**/_*', '**/.*', 'readme.md', 'yarn.lock'],
  reshape: htmlStandards({
    // locals: (ctx) => { return { pageId: pageId(ctx), foo: 'bar' } },
    parser: false,
    locals
  }),
  postcss: cssStandards(),
  babel: { presets: [[jsStandards, { modules: false }]], plugins: [dynamicImport] },
  plugins: [
    new Rooftop({ addDataTo: locals, name: 'test', url: 'https://rooftop-cms.xxxx.eu', apiToken: '95ac32241XXXXXXXXd9fbe092f', contentTypes: [{ name: 'posts', template: {path: 'templates/post.html',output: (post) => { return `posts/${post.slug}.html` }}}] })
  ]

}

**Comment by jescalan** [comment] 2017-07-06 13:48
Ah I don't think the rooftop plugin has been updated recently to work with the latest version of spike. Let me take a look at this now.

**Comment by jalbstmeijer** [comment] 2017-07-06 13:49
Yes, that was my first idea too, but downgrading to spike-1.0.0 gives the same result.

**Comment by jescalan** [comment] 2017-07-06 13:58
yeah rooftop was pre-1.0. just found the issue and fixed it, will push in a minute. tbh, we ended up switching off of rooftop due to a number of issues so it just hasn't been a priority keeping that plugin up to date.

**Comment by jescalan** [comment] 2017-07-06 14:01
Also, I reproduced your error message and there is also an extensive stack trace pointing to the exact location of the issue, not just an ID. Including that would have certainly given a more accurate context...

**Comment by jescalan** [comment] 2017-07-06 14:03
Ok just published a new version of spike-rooftop, give that a shot and it should close this out!

**Comment by jalbstmeijer** [comment] 2017-07-06 18:36
using pip till now, I suppose I have to checkout the master branch instead?

**Comment by jescalan** [comment] 2017-07-06 18:49
Hm? no you can just update the dependency in your package.json file. If you are using yarn, you can run the lovely `yarn upgrade-interactive` command to do so. Otherwise you can manually switch the semver number to `^1.0.0` and run `npm i`.

**Comment by jalbstmeijer** [comment] 2017-07-07 18:23
Hi,

Still getting the same error with spike-2.0.0 and spike-rooftop-1.0.0.
Only thing that makes me wander is why spike-1.3.1 is listed inside the project folder created  with spike-2.0.0.

spike new website
cd website
npm list spike
@0.0.1 /home/user/website
`-- spike@1.3.1 

just running spike, shows version 2.0.0.
spike --version
2.0.0

should I move this to the spike-rooftop github project?

**Comment by jescalan** [comment] 2017-07-07 18:26
> Only thing that makes me wander is why spike-1.3.1 is listed inside the project folder created with spike-2.0.0.

Good call, just hadn't updated the default template yet, I just updated it now. Thanks for catching that!

> should I move this to the spike-rooftop github project?

And yeah that would be great. All the tests are passing with spike-rooftop on the latest version, so I'm a little confused as to how that error wold be appearing... can you give me a full trace or perhaps reach out privately on gitter and get me the source so I can test it?

**Closed as completed** 2017-08-03 14:03 UTC
