### ISSUE TITLE
No watch support for app.js?

### ISSUE THREAD

**Issue by bangzek** [static-dev/spike#76] opened 2017-08-02 10:13 UTC
I use each expression on index.sgr taking data from app.js locals, the problem is if I update app.js (add another item on the array) then index pages is not updated even when I manually reload it.

I must stop and start spike watch or run spike compile for every changes.

**Comment by jescalan** [comment] 2017-08-02 23:42
Hey there @bangzek -- yes if you change the core config file you need to restart the watcher. This is the case for just about any framework out there. Triggering a reload of the entire config is possible, but would be quite difficult. If it's something you are really interested in, I'd be happy to take a look at a pull request!

**Comment by bangzek** [comment] 2017-08-03 03:58
Seem like a worthy goal, but I've got a long way to go.
Must understand this webpack thingy and getting my feet wet on nodejs scripting.

Don't close this bug yet.
Who knows maybe in a year I might close it :^)

**Comment by jescalan** [comment] 2017-08-03 14:02
So it's not a bug, it's a feature request. I am going to close it though, I'm sorry -- if you do end up coming back in a year to look at it we can re-open it then. For now it helps me a lot to only have issues open that are being worked on 😁

**Closed as completed** 2017-08-03 14:02 UTC
