### ISSUE TITLE
[reshape-layouts] Block inside of a <title> tag

### ISSUE THREAD

**Issue by jannisg** [static-dev/spike#31] opened 2016-09-27 05:28 UTC
I'm trying to configure the default `spike new` output to be running via the default reshape parser instead of the `sugarml` parser but can't seem to get it running correctly with the following changes to my files:

`app.js`:

``` javascript
...
matchers: {
    html: '*(**/)*.html',
    css: '*(**/)*.sss'
},
ignore: ['**/layout.html', '**/_*', '**/.*', '_cache/**', 'readme.md'],
reshape: (ctx) => {
  return htmlStandards({
    webpack: ctx,
    locals: { pageId: pageId(ctx), foo: 'bar' },
    parser: false
  })
},
...
```

In my `views` folder I have added 2 files:

`layout.html`

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Site - <block name="title">Layout</block></title>
</head>
<body>
  <block name="content"></block>
</body>
</html>
```

`index.html`

``` html
<extends src="layout.html">
  <block name="title">Hello from the index page</block>
  <block name="content">
    <h1>The title of the index page</h1>
  </block>
</extends>
```

My assumption was that making these changes while passing the `parser: false` option to the `htmlStandards` function should trigger the documented default parser as per the `layouts` docs here:  https://github.com/reshape/layouts

The output when running `spike watch` is not throwing any errors but at `localhost:1111` I just see the exact contents of `index.html` and not the extended `layout.html` with contents provided via the `index.html` file as I would've assumed it should work.

Is this a bug or am I misusing/misconfiguring the tool here?

---

Node version: `v6.4.0`
Spike version: `0.12.1`

**Comment by jescalan** [comment] 2016-09-27 15:50
Hey @jannisg -- give the [sugarfree template](https://github.com/static-dev/spike-tpl-sugarfree) a look and see if this solves your issue!

**Comment by jannisg** [comment] 2016-09-29 20:42
@jescalan Thanks for the reply, been playing with the sugarfree template and done a comparison between the markup I had in my files in the other template and now this (working) sugarfree template and have found that it seems the `<block name>` definition tags are only working in some contexts.

---

**Example:**

`layout.html` — _works_

``` html
<!DOCTYPE html>
<html>

  <head>
    <block name='title'></block>
  </head>

  <body role='document'>
    <block name='content'></block>
  </body>

</html>
```

with `index.html`

``` html
<extends src='layout.html'>
  <block name='title'>
    <title>Hello from the index page</title>
  </block>
  <block name='content'>
    <h1>The title of the index page</h1>
  </block>
</extends>
```

This works fine however, if I try and give my site a common `<title>` prefix by nesting the `<block name='title">` inside the layout's `<title>` tag things start breaking (see below):

---

**Non working example:**

`layout.html` — _not working with nested tags_

``` html
<!DOCTYPE html>
<html>

  <head>
    <title>
      MySitePrefix - <block name='title'></block>
    </title>
  </head>

  <body role='document'>
    <block name='content'></block>
  </body>

</html>
```

`index.html`

``` html
<extends src='layout.html'>
  <block name='title'>Hello from the index page</block>
  <block name='content'>
    <h1>The title of the index page</h1>
  </block>
</extends>
```

---

**Error thrown in console:**

``` bash
✗ ERROR
Error: ModuleBuildError: Module build failed: ReshapePluginError: Block "title" doesn't exist in the layout template
From Plugin: reshape-extend
Location: /Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/views/index.html:2:3

   1. | <extends src='layout.html'>
 > 2. |   <block name='title'>Hello from the index page</block>
      |   ^
   3. |

    at mergeExtendsAndLayout (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:81:11)
    at tree.reduce (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:51:18)
    at Array.reduce (native)
    at handleExtendsNodes (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:26:15)
    at ReshapeLayouts (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:16:12)
    at W.reduce (/usr/local/lib/node_modules/spike/node_modules/reshape/lib/index.js:43:60)
    at tryCatchResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:588:4)
    at SpikeError (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/errors.js:14:5)
    at Spike.compileCallback (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/index.js:168:31)
    at Watching._done (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:81:7)
    at Watching.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:55:25)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:227:18)
    at Compiler.next (/usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:64:18)
    at processedFiles.forEach (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/plugin.js:59:31)
    at Array.forEach (native)
    at Compiler.compiler.plugin (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/plugin.js:52:22)
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:54:18)
    at /usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:71:13)
⚠ WARNING
Error: ./views/index.html
Module build failed: ReshapePluginError: Block "title" doesn't exist in the layout template
From Plugin: reshape-extend
Location: /Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/views/index.html:2:3

   1. | <extends src='layout.html'>
 > 2. |   <block name='title'>Hello from the index page</block>
      |   ^
   3. |

    at mergeExtendsAndLayout (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:81:11)
    at tree.reduce (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:51:18)
    at Array.reduce (native)
    at handleExtendsNodes (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:26:15)
    at ReshapeLayouts (/Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/reshape-layouts/lib/index.js:16:12)
    at W.reduce (/usr/local/lib/node_modules/spike/node_modules/reshape/lib/index.js:43:60)
    at tryCatchResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/local/lib/node_modules/spike/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/local/lib/node_modules/spike/node_modules/when/lib/makePromise.js:588:4)
 @ multi views/index.html
    at SpikeError (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/errors.js:14:5)
    at SpikeWarning (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/errors.js:28:1)
    at Spike.compileCallback (/usr/local/lib/node_modules/spike/node_modules/spike-core/lib/index.js:174:26)
    at Watching._done (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:81:7)
    at Watching.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:58:19)
    at /usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:267:14)
    at /usr/local/lib/node_modules/spike/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/spike/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/spike/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/jannis/Sites/spike-test-sugarfree/sugarfree-test/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/spike/node_modules/graceful-fs/graceful-fs.js:43:10
compiled (0.038s)
```

---

My understanding based on the Usage example for [Reshape's Layout plugin](https://github.com/reshape/layouts) was that nesting the `<block>` within `<title>` should work as expected.

Is this simply a bug or am I missing something here?

**Comment by jescalan** [comment] 2016-10-10 18:33
Hey there! Sorry for the super late response here. So I did a bit of testing and it looks like there is a bug, but it's not exactly with what you pointed out here. Let me walk you through my path digging deeper this, because these are the next steps you could take to file a more accurate bug report (that being said, this one was already quite good, so thank you!)

What's interesting is that if you remove the `<title>` tag in your broken template as such:

``` html
<!DOCTYPE html>
<html>

  <head>
      MySitePrefix - <block name='title'></block>
  </head>

  <body role='document'>
    <block name='content'></block>
  </body>

</html>
```

...it suddenly works. But of course, this is not reasonable, you do want it inside that title tag. So it seemed to me like the title tag specifically was what was causing the issue. Let's make sure:

``` html
<!DOCTYPE html>
<html>

  <head>
    <title1>
      MySitePrefix - <block name='title'></block>
    </title1>
  </head>

  <body role='document'>
    <block name='content'></block>
  </body>

</html>
```

...this also works perfectly fine. So it seems like having the tag named "title" specifically is the cause of the issue. Now my next question is whether the "title" tag would always cause an issue, or if it was conflicting somehow with the name of the block (also "title") which was causing the issue. So next to try out was changing the name of the block `title` to something like `title1`. I won't paste the code again you get the idea.

Surprisingly, this still didn't work. The only way I was able to reliably produce the error was if there was a block inside of a tag called `title`. Very unusual. Any other name on the tag, it would work perfectly fine.

Beyond this, it requires diving into the internals. I'll do this shortly and get back to you with what's hopefully a patch for the issue 😁

**Comment by jescalan** [comment] 2016-10-10 18:58
Ok, dug a little deeper and I think I see the issue. We use [parse5](https://github.com/inikulin/parse5) to parse html for reshape, and this parser is fairly strict about HTML rules. One of these rules is that there cannot be a tag nested inside of a title tag, which makes a lot of sense. So instead of actually parsing the title block as a tag, it is parsed as plaintext, causing the layouts plugin to not be able to find the block, which explains the error being thrown.

I'm not entirely sure how we can resolve this specific issue, but will bring it up with the parse5 maintainers and see what they think!

**Comment by jescalan** [comment] 2016-10-10 19:11
ref https://github.com/inikulin/parse5/issues/158

**Comment by jescalan** [comment] 2016-10-10 20:46
Hey there @jannisg -- so my suggestion to immediately fix the issue is to wrap the entire title tag in a block as such:

``` html
<block name='title'>
  <title>Your Custom Title</title>
</block>
```

If you have a default prefix you want to use for all pages, you could add this as a local:

``` html
<block name='title'>
  <title>{{ defaultTitle }}: Your Custom Title</title>
</block>
```

Also @wooorm suggested in the other thread that we could add a new feature that would provide an alternate solution to the issue:

``` html
<title block-name="title"></title>
```

So this would, instead of using a separate block element, replace the contents of the element the attribute is on with the given contents. Any interest in this?

I think the solution to this issue at the moment, however, is to throw an explicit error when text-only tags like `<title>` contain blocks, since this is not possible with our parser.

**Comment by jannisg** [comment] 2016-10-20 06:00
@jescalan Thanks so much for further investigating this. I will happily use these workarounds for now.

In terms of the `block-name` suggestion, I do like this a lot but would say that given my specific scenario here about being able to add a prefix of some sort, allowing something like the following would be nice:

``` html
<title block-name="title" block-prefix="My Site - "></title>
```

One thing I would strongly suggest is updating the https://github.com/reshape/layouts docs since they specially use the `<title>` in the wrong way. If you're open to this, I'm happy to send the changes to the example markup in the readme via a PR.

**Comment by jannisg** [comment] 2016-10-20 06:29
I was just going to put a PR together for https://github.com/reshape/layouts/blob/master/README.md when I realised that the updates to the README.md would also have to address the `prepend` and `append` options, so since the the `<title>` tag is now within the `<block name="title">` the example will no longer work as expected.

Any thoughts on how the `prepend` and `append` functionality might be worked around? I assume locals would be the only option?

**Comment by jescalan** [comment] 2016-10-20 14:44
@jannisg Ah good call! I'll update the readme right now, thanks for catching this. And yeah, at the moment I'm afraid the locals method might be the only way to do it!

**Comment by jannisg** [comment] 2016-11-15 00:32
Was about to close the issue, but figured I leave it open (unless you want to close it) until the reshape/layouts README section for "Append & Prepend" is also updated as it still contains references to prepend something to the title which won't work with the bug.

**Comment by jescalan** [comment] 2016-11-15 15:38
@jannisg I must have missed this, would you be willing to submit a PR to fix it? 😁

**Comment by alexpate** [comment] 2017-04-22 11:29
Is there a suggested workaround for this? Running into the same problem at the moment

**Comment by jescalan** [comment] 2017-04-22 16:05
@alexpate yep! https://github.com/static-dev/spike/issues/31#issuecomment-252741415

**Comment by jescalan** [comment] 2017-08-03 14:11
Going to close this since this is part of the behavior of our html parser and will not be fixed, and the reshape/layouts docs have been updated 🙌

**Closed as completed by jescalan** 2017-08-03 14:11 UTC
Labels: bug
